### ISSUE TITLE
Elitra swap request (and please add config if you can)

### ISSUE THREAD

**Issue by MAGGen-hub** [StephenBarnes/ArmorExchanger#1]
Why can't I swap my elitra? If you can please fix it... I will try to implemet that feachue from another armor swapper and make pull request (if I found it's source code). Also I will test your mod without my mod-set to be sure the problem is not in my mods. And please make config for you mod if you can (something like black and white list for items that can or can't be swapped). Thanck you for attantion.

**Comment by MAGGen-hub** [comment]
In file named ModEventHandler.java you need to chager 22 code string from this:

`
if (!(item instanceof ArmorItem)) return;`

to this
`
if (!(item instanceof ArmorItem) && !(item instanceof ElytraItem)) return;`

this will fix the Elytra problem... But it's only minor fix... We still need the cfg file to change the list of auto-swappable items...
For example you still can't swap pumpkins)

**Comment by MAGGen-hub** [comment]
Whops! Wrong fix... Silly me.. Hehe... You need to change || (or) to && (and)... 
I reedit my comment... So now everything is normal)

**Comment by MAGGen-hub** [comment]
Found a bug... You can unequip cursed items, so you need to check that. Add anoter if that check item for BINDING_CURSE. And making swap unable if player equped cursed item.

**Comment by MAGGen-hub** [comment]
Check this mod: https://github.com/kregerl/armorhotswap
May be you need to cooperate with it's author to make your projects better? You and his mods still has bugs... I more than sure if you cooperate with him you two can make better armor swap mods for forge version of minecraft. For my opinion it's not right that fabric version of armor-swap (Inventory Control Tweaks) is still better than forge... Pls make forge better...

**Comment by StephenBarnes** [comment]
Ah thanks, should have tested this more. I searched CurseForge for "armor swap" etc. but that mod didn't come up, if I knew about it I wouldn't have written this. So I think I'm going to abandon this project and point people to Armor Hotswap instead, and maybe make PRs to fix the one or two bugs in that one.

**Comment by MAGGen-hub** [comment]
I merged your mod and another one with same functional.
Some minor improvements and bugfixes for 1.16.1 version of the game.
Please see my code on https://github.com/MAGGen-hub/Armor-Exchanged-Super-Hot-Swap and use it in your mod if you want.
After that my version of armor-swap can be deleted.
Thanck you for your attantion and sorry for my weird English.

**Comment by MAGGen-hub** [comment]
Sorry for weird mod name. But I am not good at name making)))

**Comment by StephenBarnes** [comment]
Nice, thank you! Did you already put this on CurseForge as a separate mod? Or do you want me to upload it?

**Comment by MAGGen-hub** [comment]
It's on curseforge. You can upload your mod using my code if you want. I think I need to make a modpack... Well I mean fabric already have very well made InventoryTweaksPack and I want to make something like that on forge: just imagine InventoryTweaks InventorySorter ArmorSwap MouseTweaks and others in one mod. I think minecraft realy need lots of improevements in it inventory systems. Terraria and other blocky games already have perfect sorting systems... But Minecraft (What the hell is wrong with Mojang?!) still has this old looking system (no sorting no fast items replace no etc.)...

**Comment by StephenBarnes** [comment]
Great, thanks. Agree we need something like that for Forge. I updated my mod description on CurseForge to send people to use this one instead.
